language: scala

scala:
    - 2.10.4
    - 2.11.2

jdk:
    - openjdk6
    - oraclejdk7
    - oraclejdk8

env:
    global:
        secure: "EsZUoN3laiGZTJIxfJtmc72QemC+waG/YIuQpSqAguS0OAfFVB1HM3A7TkhbNAFvM5HRFfpE4vU1/qcG4PATyZEtvHqBnxcZ0eAu+6DzAXqnroudF3ShgbT0YTMf1Izpd0tpiN+wBa4xSXWP9fEg432m53ZeevsJqDi68Q/5DXA="

script: ./sbt ++$TRAVIS_SCALA_VERSION compile scoverage:test
